title: Welcome to my world
hero_image: images/banner.png
description: Build a 2.5D world to explore and interact with.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test
  - title: Share
  - title: Upgrade your project
  - title: Reflect
  - title: What next?
