---
title: مرحبا بك في عالمي
hero_image: images/banner.png
description: قم بإنشاء عالم 2.5D للاستكشاف والتفاعل معه.
meta_title: Scratch coding projects for kids and teens | My world
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Build a 2.5D world in Scratch to explore and interact with.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: سوف تصنع
  - 
    title: فكرتك
  - 
    title: بناء واختبار
    completion:
      - engaged
      - internal
  - 
    title: قائمة تدقيق
    completion:
      - external
  - 
    title: قم بترقية او تطوير مشروعك
  - 
    title: مشاركة
  - 
    title: ما هي الخطوة التالية؟
